#!/usr/bin/env python3
"""
Encode a file's contents as a C string literal.

This script reads an arbitrary source file and produces as output C/C++
source code that defines a string literal with the same contents as the
source file.  This allows what would otherwise be separate files to be
compiled into an executable, easing deployment.
"""

from __future__ import annotations
import sys
from pathlib import Path


def usage(prog_name: str) -> None:
  print(f"""usage: {prog_name} <arrayName> <inFile> <outHeader> <outCode>

Reads <inFile>, writes <outHeader> and <outCode>.
<outHeader> declares a char array called <arrayName>.
<outCode> defines that char array.
""")


# TODO: Change the terminology to "bytes", not "characters".
def encode_file_to_c_lines(infile: Path) -> tuple[list[str], int]:
  """Read binary data from `infile` and return (encoded_lines,
  num_characters)."""

  # Lines of encoded characters.
  out_lines: list[str] = []

  # Current encoded output line.
  cur_line: str = ""

  # Total number of characters.
  num_characters = 0

  with infile.open("rb") as f:
    while True:
      buf = f.read(4096)
      if not buf:
        break
      num_characters += len(buf)
      for b in buf:
        if b == 10:  # newline
          # At newlines, encode it, and also break the string literal so
          # that the output is not all on one line.
          cur_line += "\\n"
          out_lines.append(cur_line)
          cur_line = ""

        elif b == ord('"'):
          cur_line += '\\"'

        elif b == ord("\\"):
          cur_line += "\\\\"

        elif 32 <= b < 127:
          cur_line += chr(b)

        else:
          # Use octal rather than hex because hex would continue if the
          # next character happened to also be valid hex.
          cur_line += f"\\{b:03o}"

  # Final line; might be empty, which is fine, and handles the
  # degenerate case of an empty input file.
  out_lines.append(cur_line)
  return out_lines, num_characters


def write_header(
  out_header: Path,
  array_name: str,
  in_file: Path,
  array_size: int,
  argv: list[str],
) -> None:
  """Write a header file called `out_header` that goes with the source
  file that `write_code` creates."""

  # Name of the #inclusion guard symbol: uppercase, with non-alnum
  # replaced with underscores.
  guard_name = out_header.name.upper()
  guard_name = "".join(ch if ch.isalnum() else "_" for ch in guard_name)

  with out_header.open("w", encoding="utf-8", newline="\n") as out:
    out.write(f"""// {out_header}
// header file generated by {argv[0]} {' '.join(argv[1:])}

#ifndef {guard_name}
#define {guard_name}

// contents of {in_file}, plus an extra NUL byte
extern char const {array_name}[{array_size}];

#endif // {guard_name}
""")


def write_code(
  out_code: Path,
  out_header: Path,
  array_name: str,
  in_file: Path,
  array_size: int,
  out_lines: list[str],
  argv: list[str],
) -> None:
  """Write a source code file called `out_code` that defines an array
  called `array_name` of size `array_size` that encodes the contents of
  `in_file`.  The encoded contents are in `out_lines`.

  The corresponding declaration is the file `out_header`.  Include a
  comment with `argv`, the command line of the script (this script) that
  did the encoding."""


  with out_code.open("w", encoding="utf-8", newline="\n") as out:
    out.write(f"""// {out_code}
// code file generated by {argv[0]} {' '.join(argv[1:])}

#include "{out_header.name}"             // decl of {array_name}

// contents of {in_file}, plus an extra NUL byte
char const {array_name}[{array_size}] =
""")

    for enc_line in out_lines:
      out.write(f'  "{enc_line}"\n')

    out.write("  ;\n\n// EOF\n")


def main(argv: list[str]) -> int:
  if len(argv) != 5:
    usage(argv[0])
    sys.exit("script must be called with exactly 4 arguments")

  _, array_name, in_file_str, out_header_str, out_code_str = argv
  in_file = Path(in_file_str)
  out_header = Path(out_header_str)
  out_code = Path(out_code_str)

  out_lines, num_chars = encode_file_to_c_lines(in_file)

  # Size of the output array.  It is one more than the source file's
  # size because (a) the array literal syntax requires an implicit NUL
  # byte at the end (C++03 8.5.2/2), and (b) it is often convenient
  # to have the extra NUL anyway, so the contents can be used with
  # standard string-manipulation functions.  When dealing with binary
  # data, clients must be aware that the extra NUL byte is always
  # present, and was not in the original file.
  array_size = num_chars + 1

  write_header(out_header, array_name, in_file, array_size, argv)
  write_code(out_code, out_header, array_name, in_file, array_size, out_lines, argv)

  print(f"encoded {num_chars} bytes in {out_header} and {out_code}")
  return 0


if __name__ == "__main__":
  sys.exit(main(sys.argv))


# EOF
