// syserr.h            see license.txt for copyright and terms of use
// Portable encapsulation of system-dependent error facilities like
// UNIX's errno and Win32's GetLastError().

// The intent here is to provide a way for portable *handling* of errors
// that are generated by nonportable code.

#ifndef SMBASE_SYSERR_H
#define SMBASE_SYSERR_H

// Note: This module is meant to have a minimum of dependencies since it
// is needed by low-level code that directly queries the OS.

#include "smbase/exc.h"                // smbase::XBase
#include "smbase/sm-macros.h"          // OPEN_NAMESPACE, NORETURN

#include <iosfwd>                      // std::ostream
#include <string>                      // std::string


OPEN_NAMESPACE(smbase)


// Portable failure reasons (modeled loosely on errno.h).
//
// It is anticipated that, as certain errors become important on
// certain platforms, that this list will be extended as necessary.
enum class SysErrorReasonCode : int {
  R_NO_ERROR,          // no error occurred

  // TODO: Combine the next two.
  R_FILE_NOT_FOUND,    // We sometimes get this when R_PATH_NOT_FOUND might be expected...
  R_PATH_NOT_FOUND,

  R_ACCESS_DENIED,
  R_OUT_OF_MEMORY,
  R_SEGFAULT,          // invalid address / pointer
  R_FORMAT,            // bad data format
  R_INVALID_ARGUMENT,
  R_READ_ONLY,
  R_ALREADY_EXISTS,
  R_AGAIN,             // resource temporarily unavailable
  R_BUSY,              // resource busy
  R_INVALID_FILENAME,  // too long, bad chars, etc.
  R_UNKNOWN,           // OS-specific, can't find out, just don't know, etc.
  NUM_REASONS          // (must be last item in list)
};

// Return a string like "R_NO_ERROR", or "<invalid>" if `r` is out of
// bounds.
char const *toString(SysErrorReasonCode r);

// Write `toString(r)`.
std::ostream &operator<<(std::ostream &os, SysErrorReasonCode r);

// Human-readable string like "File not found".
char const *reasonCodeDescription(SysErrorReasonCode r);


// Thrown in response to a system call failure.
class XSysError : public XBase {
public:      // instance data
  // Portable reason code corresponding to the platform-specific error
  // code.
  SysErrorReasonCode reason;

  // Reason string that corresponds to 'reason'.
  //
  // TODO: Remove this.
  char const * const reasonString;

  // Platform-specific error code: errno on Unix, GetLastError() on
  // Windows.  The value is 0 when we don't have this information.
  //
  // TODO: When do we not have it?
  //
  // TODO: Change to std::optional<uint32_t>.
  int sysErrorCode;

  // Platform-specific reason string given by the OS, if any (might be
  // empty).
  std::string sysReasonString;

  // Name of syscall or API function name, as specific in the ctor
  // arguments.
  std::string syscallName;

  // Error context, as specified in the ctor arguments.  This should be
  // additional context details like the name a file we were trying to
  // open.  May be empty.
  //
  // TODO: I should remove this and put the information into
  // `XBase::m_contexts` instead.
  std::string context;

public:      // methods
  XSysError(
    SysErrorReasonCode r,
    int sysCode,
    std::string const &sysReason,
    std::string const &syscall,
    std::string const &ctx);

  XSysError(XSysError const &obj);

  ~XSysError();

  // XBase methods.
  virtual std::string getConflict() const override;

  // TODO: Move most of the static methods out of the class.

  // Retrieve the platform-specific error code.
  static int getSystemErrorCode();

  // Return a portable equivalent of `sysErrorCode`.  Returns R_UNKNOWN
  // if the code is not recognized.  Sets `sysReason` to the system's
  // message string, if possible.
  //
  // TODO: When is that not possible?  And what happens to `sysReason`
  // in that case?
  static SysErrorReasonCode portablize(
    int sysErrorCode, std::string &sysReason);

  // Construct the string we use as the `getMessage()` of XBase.  If
  // `ctx` is empty, the string doesn't include it.
  static std::string constructWhyString(
    SysErrorReasonCode r,
    std::string const &sysReason,
    std::string const &syscall,
    std::string const &ctx);

  // Construct and throw an `XSysError`.
  static void xsyserror(
    std::string const &syscallName,
    std::string const &context) NORETURN;
};


// Construct and throw an `XSysError`.
void xsyserror(char const *syscallName) NORETURN;
void xsyserror(
  std::string const &syscallName,
  std::string const &context) NORETURN;


// Get the message string that would be created if an `XSysError` were
// built while the system's error code was `systemErrorCode`.
std::string sysErrorCodeString(
  int systemErrorCode,
  std::string const &syscallName,
  std::string const &context);

// Get the message string for the current system error code.
std::string sysErrorString(
  char const *syscallName,
  char const *context = nullptr);


// Issue a "developer warning" about a system call that just failed.
//
// This is useful when we don't want to stop what we are doing (perhaps
// because the system call failure doesn't impede progress, for example
// failing to close a resource), but still want an alert that could aid
// diagnosis and amplfy testing efforts.
void devWarningSysError(
  char const *file,
  int line,
  char const *syscallName,
  char const *context = nullptr);

#define DEV_WARNING_SYSERROR(syscall) \
  smbase::devWarningSysError(__FILE__, __LINE__, syscall) /* user ; */

#define DEV_WARNING_SYSERROR_CTXT(syscall, context) \
  smbase::devWarningSysError(__FILE__, __LINE__, syscall, context) /* user ; */


CLOSE_NAMESPACE(smbase)


#endif // SMBASE_SYSERR_H
