// out/test/fts/allbytes.bin.h
// header file generated by ./file-to-strlit.py arr test/fts/in/allbytes.bin out/test/fts/allbytes.bin.h out/test/fts/allbytes.bin.c

#ifndef ALLBYTES_BIN_H
#define ALLBYTES_BIN_H

// contents of test/fts/in/allbytes.bin, plus an extra NUL byte
extern char const arr[273];

#endif // ALLBYTES_BIN_H
