// out/test/fts/hex-escape-problem.bin.c
// code file generated by ./file-to-strlit.py arr test/fts/in/hex-escape-problem.bin out/test/fts/hex-escape-problem.bin.h out/test/fts/hex-escape-problem.bin.c

#include "hex-escape-problem.bin.h"             // decl of arr

// contents of test/fts/in/hex-escape-problem.bin, plus an extra NUL byte
char const arr[25] =
  "CR then '0' then NL:\n"
  "\0150\n"
  ""
  ;

// EOF
