// out/test/fts/hex-escape-problem.bin.h
// header file generated by ./file-to-strlit.py arr test/fts/in/hex-escape-problem.bin out/test/fts/hex-escape-problem.bin.h out/test/fts/hex-escape-problem.bin.c

#ifndef HEX_ESCAPE_PROBLEM_BIN_H
#define HEX_ESCAPE_PROBLEM_BIN_H

// contents of test/fts/in/hex-escape-problem.bin, plus an extra NUL byte
extern char const arr[25];

#endif // HEX_ESCAPE_PROBLEM_BIN_H
