// out/test/fts/noheader.txt.c
// code file generated by ./file-to-strlit.py arr test/fts/in/noheader.txt - out/test/fts/noheader.txt.c

// contents of test/fts/in/noheader.txt, plus an extra NUL byte
extern char const arr[34] =
  "This will not get a header file.\n"
  ""
  ;

// EOF
